export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header style={{
        backgroundColor: "lightblue",
        fontSize:"2rem",
        padding: "4px"
      }}>header</header>
      <body>{children}</body>
      <footer style={{
        backgroundColor: "ghostwhite",
        fontSize:"2rem",
        padding:"4px"
      }}>footer</footer>
    </html>
  )
}
