import { Metadata } from "next"


export const metadata: Metadata = {
  title: {
    template: "%s | halulabs",
    default: "halulabs website",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor:"lightblue",
          padding:"1rem",
          fontSize:"2rem"
        }}>header</header>
        {children}
        <footer style={{
          backgroundColor:"ghostwhite",
          padding:"1rem",
          fontSize:"2rem"
        }}>footer</footer>
      </body>
    </html>
  )
}
